"use strict";
app
.factory("Store",	function () {
	var Store = [
		 {
		 	"id" : 1,
		   "name": "Outcast",
		   "address": "สยามสแควร์",
		   "type": 1,
		   "storeType": "ร้านเสื้อผ้าแฟชั้น",
		   "rentType": "แบ่งพื้นที่ภายในร้าน",
		   "description": "เป็นร้านขายเสื้อผ้าแฟชั่นแนวสตรีท นอกกระแส ที่รวมหลายๆยี่ห้อ มาวางไว้ที่เดียว ทั้งของต่างประเทศและของไทย โดยเน้นยี่ห้อที่มีความแตกต่าง  และหาได้ยาก ชั้นหนึ่งวางของต่างประเทศ ชั้นสองวางของไทย \n\nบริเวณที่ต้องการปล่อยเช่า อยู่ชั้นสอง พื้นที่ 2x2 เมตร บริเวณติดผนัง มีราวแขวน ไม้แขวานเสื้อพร้อม สามารถแขวนเสื้อได้ประมาณ 20 ตัว และเก็บสต็อคได้ประมาณ 60 ตัว\n",
		   "amenities": ["แอร์" , "ราวแขวนเสื้อ" , "ไม้แขวนเสื้อ"],
		   "rule": "ไม่ขายของปลอม , ไม่ขายของผิดกฏหมาย",
		   "images" : [
		   		'images/innovator/1/01.jpg',
		   		'images/innovator/1/02.jpg',
		   		'images/innovator/1/03.jpg',
		   		'images/innovator/1/04.jpg',
		   		'images/innovator/1/05.jpg',
		   		'images/innovator/1/06.jpg',
		   		'images/innovator/1/07.jpg',
		   		'images/innovator/1/08.jpg',
		   		'images/innovator/1/09.jpg',
		   		'images/innovator/1/10.jpg',
		   		'images/innovator/1/11.jpg',
		   		'images/innovator/1/12.jpg',
		   		'images/innovator/1/13.jpg',
		   		'images/innovator/1/14.jpg',
		   		'images/innovator/1/15.jpg',
		   	],
		   	"position" : "13.750764, 100.532439",
		   	"price" : 1500
		 },
		 {
		 	"id" : 2,
		   "name": "Mango Mojito",
		   "address": "สยามสแควร์",
		   "type": 1,
		   "storeType": "ร้านเสื้อผ้าแฟชั้น",
		   "rentType": "แบ่งพื้นที่ภายในร้าน",
		   "description": "ร้านเราเน้นดีไซน์เรียบหรู สไตล์อิตาลี ขายรองเท้าทำงานสไตล์อิตาลี มีดีไซน์เนอร์เป็นคนอิตาลี และคนไทย \n\nเราขอปล่อยให้สินค้าเสื้อสูทเท่านั้น ที่สามารถวางขายในร้านได้ โดยพื้นที่ปล่อยเช่า อยู่บริเวณด้านหน้าสุดของร้าน คนเดินผ่านจะมองเห็นเด่นชัด พร้อมมีหุ้นโชว์ เพื่อสวมใส่เสื้อสูท และชั้นวางของ เพื่อวางของตกแต่งเพิ่มเติม \n",
		   "amenities": ["หุ่นโชว์" , "ชั้นวางของตกแต่ง" , "แอร์"],
		   "rule": "ให้ขายได้เฉพาะชุดสูท , ไม่ขายของปลอม , ไม่ขายของผิดกฏหมาย",
		   "images" : [
		   		'images/innovator/2/01.jpg',
		   		'images/innovator/2/02.jpg',
		   		'images/innovator/2/03.jpg',
		   		'images/innovator/2/04.jpg',
		   		'images/innovator/2/05.jpg',
		   		'images/innovator/2/06.jpg',
		   		'images/innovator/2/07.jpg',
		   		'images/innovator/2/08.jpg',
		   		'images/innovator/2/09.jpg',
		   		'images/innovator/2/10.jpg',
		   		'images/innovator/2/11.jpg',
		   		'images/innovator/2/12.jpg',
		   		'images/innovator/2/13.jpg',
		   		'images/innovator/2/14.jpg',
		   		'images/innovator/2/15.jpg',
		   		'images/innovator/2/16.jpg',
		   		'images/innovator/2/17.jpg',
		   	],
		   	"position"	: "13.745030, 100.533076",
		   	"price" : 1000
		 },
		 {
		   "id" : 3,
		   "name": "Denta Club",
		   "address": "สยามสแควร์",
		   "type": 1,
		   "storeType": "ร้านเสื้อผ้าแฟชั้น",
		   "rentType": "แบ่งพื้นที่ภายในร้าน",
		   "description": "ร้านอยู่ติดทางเดินระหว่าง มาบุญครองไปสยามสแควร์ ส่วนใหญ่เป็นคนต่างชาติ ติดถนนใหญ่ เน้นขายเสื้อยืดลายข้อความภาษาไทย เรามีร้านกาแฟอยู่ภายในร้านอีกด้วย\n\nพื้นที่ให้เช่า เป็นราวแขวนเสื้อ ประมาณ 2 เมตร สามารแขวนเสื้อได้ประมาณ 20 ตัว และวางสต็อคได้ 60 ตัว มีไม้แขวนบริการ",
		   "amenities": ["ราวแขวนเสื้อ" , "ไม้แขวนเสื้อ" , "ร้านกาแฟ" , "แอร์"],
		   "rule": "ไม่ขายของปลอม , ไม่ขายของผิดกฏหมาย",
		   "images" : [
		   		'images/innovator/3/01.jpg',
		   		'images/innovator/3/02.jpg',
		   		'images/innovator/3/03.jpg',
		   		'images/innovator/3/04.jpg',
		   		'images/innovator/3/05.jpg',
		   		'images/innovator/3/06.jpg',
		   		'images/innovator/3/07.jpg',
		   		'images/innovator/3/08.jpg',
		   		'images/innovator/3/09.jpg'
		   	],
		   	"position"	: "13.733972, 100.527938",
		   	"price" : 1500
		 },
		 {
		 	"id" : 4,
		   "name": "BOYLONDON ",   
		   "address": "สยามสแควร์",
		   "type": 1,
		   "storeType": "ร้านเสื้อผ้าแฟชั้น",
		   "rentType": "แบ่งพื้นที่ภายในร้าน",
		   "description": "ในร้านบอยลอนดอนที่มีคนหลงรัก korean street fashion เรามีที่ห้องเป็นโชว์รูมส่วนตัวแบ่งให้คุณเข้ามาเป็นส่วนร่วมกับเรา เหมาะกับ เปิดตัวสินค้าใหม่ หรือ แนะนำสินค้า ด้วยร้านที่อยู่ใจกลางสยามง่ายต่อการเดินทาง มาจาก Bts เดินแค่ 2 นาที หรือ ขับรถมาก็สามารถจอดได้ที่ใต้ตึก siam square one ได้เลย",
		   "amenities": ["ราวแขวนเสื้อ" , "ไม้แขวนเสื้อ" , "ร้านกาแฟ" , "แอร์"],
		   "rule": "ไม่ขายของปลอม , ไม่ขายของผิดกฏหมาย",
		   "images" : [
		   		'images/innovator/4/01.jpg',
		   		'images/innovator/4/02.jpg',
		   		'images/innovator/4/03.jpg',
		   		'images/innovator/4/04.jpg',
		   		'images/innovator/4/05.jpg',
		   		'images/innovator/4/06.jpg',
		   		'images/innovator/4/07.jpg',
		   		'images/innovator/4/08.jpg',
		   		'images/innovator/4/09.jpg',
		   		'images/innovator/4/10.jpg',
		   		'images/innovator/4/11.jpg',
		   		'images/innovator/4/12.jpg'
		   	],
			"position" : "13.7380032,100.5254917",
			"price" : 1500
		 },
		 {
		 	"id" : 5,
		   "name": "KLANDTH",
		   "address": "สยามสแควร์",
		   "type": 1,
		   "storeType": "ร้านเสื้อผ้าแฟชั้น",
		   "rentType": "แบ่งพื้นที่ภายในร้าน",
		   "description": "KLAND เป็นร้านเสื้อผ้า Multibrand ที่มีเสื้อผ้าหลากหลายสไตล์บินตรงจากประเทศเกาหลีเพื่อให้คุณได้ใกล้ชิดกับแฟชั่นการแต่งตัวแบบเกาหลีได้ง่ายยิ่งขึ้น  \nบรรยายการในร้าน จะมีแบร์นดดังจากเกาหลี อยู่เป็นเพือนแบร์นดที่คุณเอามาฝากขายนั่นคือ FREIKNOCK เป็นเสื้อผ้าสไตล์ Minimal ซึ่งเรียกได้ว่ากำลังเป็นสไตล์ยอดฮิตในหมู่วัยรุ่น เสื้อผ้าจะเป็นแนว Unisex เหมาะสำหรับผู้ชายที่รักในการแต่งตัวแบบเรียบง่ายแต่แฝงไปด้วยความมีสเน่ห์ และผู้หญิงที่ต้องการหนีจากความหวานและหันมาแต่งตัวให้เรียบ ดูดีและมีสไตล์  สามารถ Mix & Match ได้ง่าย นี่คือแบรนด์ที่จะมาอยู่กับแบร์นดคุณ ตามมาด้วย แบรนด์เสื้อผ้าสไตล์อาร์ตติส คุณจะหลงรักแบรนด์ SAKUN  ด้วยการออกแบบที่มีความแหวกแนว แฝงไปด้วยลูกเล่น และมีเอกลักษณ์ที่ชัดเจน บ่งบอกถึงตัวตนของความเป็นแบรนด์ได้อย่างเด่นชัดมากที่สุด  SAKUN จะทำให้คุณหลงไหลในสไตล์ของเขานอกจากนี้ยังมีแบรนด์สำหรับผู้หญิงที่ คนเกาหลียังไปเข้าคิวรอซื้อ ขอบอกว่าหายยากมาก อย่างแบรนด์ O!Oi  ซึ่งเป็นที่ชื่นชอบของสาวๆวัยใส  เพราะแบรนด์นี้มีความโดดเด่นตรงความน่ารัก สดใส และขี้เล่น  ทำให้สาวๆหลายๆคนติดใจแบรนด์นี้เป็นพิเศษ  ในแต่ละคอลเลคชั่นก็จะมีสตอรี่ในการออกแบบที่น่าจับตามอง  ทำให้สาวๆสนุกกับการแต่งตัวในแบบสาว O!Oi กันเป็นอย่างมาก ถ้าคิดถึงแฟนชั่นเกาหลี ก็จะขาดไม่ได้กับแบร์นดนี้ cresedim ใครไปถึงเกาหลีก็คงต้องเห็นคนใส่กับในทุกๆที่  และก็มาถึงแบรนด์ที่จะแนะนำสุดท้ายอย่าง CHARM’S  ซึ่งก็มีความพิเศษไม่แพ้แบรนด์อื่นๆ  CHARM’S เริ่มมาจากวงการนายแบบ นางแบบ ที่รักในการตัดเย็น ดีไซน์เสื้อผ้าที่มีเอกลักษณ์เฉพาะตัว และมีเสน่ห์ที่ไม่ซ้ำกันในแต่ละคอลเลคชั่นจะถูกพรีเซนออกมาในรูปแบบของความรักในแต่ละฤดูกาล",
		   "amenities": ["ราวแขวนเสื้อ" , "ไม้แขวนเสื้อ" , "ร้านกาแฟ" , "แอร์"],
		   "rule": "ขายสินค้าที่ไม่ผิดกฏหมาย ต้องเป็นสินค้าที่เกียวข้องกับแฟชั่นเกาหลีเท่านั้น",
		   "images" : [
		   		'images/innovator/5/01.jpg',
		   		'images/innovator/5/02.jpg',
		   		'images/innovator/5/03.jpg',
		   		'images/innovator/5/04.jpg',
		   		'images/innovator/5/05.jpg',
		   		'images/innovator/5/06.jpg',
		   		'images/innovator/5/07.jpg',
		   		'images/innovator/5/08.jpg',
		   		'images/innovator/5/09.jpg',
		   		'images/innovator/5/10.jpg'
		   	],
			"position" : "13.7380032,100.5254917",
			"price" : 1000
		 },
		 {
		 	"id" : 6,
		   "name": "Ampersand",
		   "address": "Soi Sukhumvit 39",
		   "type": 2,
		   "storeType": "ร้านไอศกรีม",
		   "rentType": "แบ่งพื้นที่ภายในร้าน",
		   "description": "Internationally Inspired Gelato. Made with organic milk.",
		   "amenities": ["แอร์"],
		   "rule": "ขายสินค้าที่ไม่ผิดกฏหมาย",
		   "images" : [
		   		'images/innovator/6/01.jpg',
		   		'images/innovator/6/02.jpg',
		   		'images/innovator/6/03.jpg',
		   		'images/innovator/6/04.jpg',
		   		'images/innovator/6/05.jpg',
		   		'images/innovator/6/06.jpg',
		   		'images/innovator/6/07.jpg',
		   		'images/innovator/6/08.jpg',
		   		'images/innovator/6/09.jpg',
		   		'images/innovator/6/10.jpg',
		   		'images/innovator/6/11.jpg',
		   		'images/innovator/6/12.jpg',
		   		'images/innovator/6/13.jpg',
		   		'images/innovator/6/14.jpg',
		   		'images/innovator/6/15.jpg',
		   		'images/innovator/6/16.jpg',
		   		'images/innovator/6/17.jpg',
		   		'images/innovator/6/18.jpg',
		   		'images/innovator/6/19.jpg',
		   		'images/innovator/6/20.jpg',
		   	],
		   	"position"	: "13.743012, 100.572025",
		   	"price" : 1000
		 },
		 {
		 	"id" : 7,
		   "name": "Two Gals And The Pig Boutique Hostel",
		   "address": "นิมมานเหมินทร์, เชียงใหม่",
		   "type": 4,
		   "storeType": "โฮสเทล",
		   "rentType": "แบ่งพื้นที่ภายในร้าน",
		   "description": "2 gals and the pig เป็นโฮสเทลที่ อยู่ใกล้แหล่งร้านอาหารมากมาย มีแขกต่างชาติเข้ามาพักตลอด พื้นที่บริเวณรอบๆตึกเป็นสนามหญ้า พร้อมโต๊ะนั่งเล่นชิวๆ ส่วนภายใน บริเวณชั้น 1 เป็นส่วนกลางของโฮสเทล ส่วน Receptionเป็นบริเวณที่แขกจะลงมานั่งพักผ่อนอยู่เสมอ อากาศถ่ายเท บรรยากาศอบอุ่น รองรับคนได้ 10-15 คน",
		   "amenities": ["โต๊ะทำงาน","โต๊ะอาหาร"," ตู้เก็บอุปกรณ์รับประทาน","ไมโครเวฟ"," ตู้วางของ","เก้าอี้","ไฟ","ทีวี"],
		   "rule": "ไม่ขายของปลอม , ไม่ขายของผิดกฏหมาย , ไม่ทำให้สถานที่เลอะเทอะ",
		   "images" : [
		   		'images/innovator/7/01.jpg',
		   		'images/innovator/7/02.jpg',
		   		'images/innovator/7/03.jpg',
		   		'images/innovator/7/04.jpg',
		   		'images/innovator/7/05.jpg',
		   		'images/innovator/7/06.jpg',
		   		'images/innovator/7/07.jpg',
		   		'images/innovator/7/08.jpg',
		   		'images/innovator/7/09.jpg',
		   		'images/innovator/7/10.jpg',
		   		'images/innovator/7/11.jpg',
		   		'images/innovator/7/12.jpg'
		   	],
		   	"position"	: "18.796021, 98.968446",
		   	"price" : 900
		 },
		 {
		 	"id" : 8,
		   "name": "The Barn : Eatery Design",
		   "address": "ถนนศรีวิชัย ซอย 5, เชียงใหม่",
		   "type": 2,
		   "storeType": "เบแกอรี่ เค้กกาแฟ",
		   "rentType": "แบ่งพื้นที่ภายในร้าน",
		   "description": "ร้านกาแฟสไตล์โรงนา สถานที่ห้ามพลาดของเหล่าฮิปสเตอร์ทั้งหลาย ตั้งอยู่ในซอยตรงข้ามคณะเภสัช มช. (ซอยไก่ทอด cmu) เข้าไปจนสุดซอยก็จะเจอร้านตั้งตระหง่านอยู่ข้างหน้าเลย เปิดตั้งแต่ 10 โมงถึงตี 1 มีที่จอดรถให้ประมาณ 7-8 คัน ร้านนี้เป็นกระแสอยู่ช่วงใหญ่เป็นที่พูดถึงของเหล่าคนชอบถ่ายรูปที่ต้องมาแวะเวียนให้ได้ ด้วยตัวร้านสร้างเป็นทรงโรงนา โปร่ง หลังคายกสูงดูแปลกตาและยิ่งถูกปกคลุมไปด้วยต้นตีนตุ๊กแกก็ยิ่งเพิ่มความคลาสสิคมากขึ้นไปอีก อุปกรณ์ในร้านเน้นเป็นวินเทจไม้ๆทำให้ถ่ายรูปออกมาแล้วสวยถูกใจใครหลายคนยิ่งนัก เมนูมีทั้งเครื่องดื่ม อาหารคาวและขนมหวาน",
		   "amenities": ["แอร์","ไฟโคม","โต๊ะ","เก้าอี้","ชั้นวางของ","ตู้เย็น","เครื่องชงกาแฟ","ลานจอดรถ"],
		   "rule": "ไม่ขายของปลอม , ไม่ขายของผิดกฏหมาย",
		   "images" : [
		   		'images/innovator/8/01.jpg',
		   		'images/innovator/8/02.jpg',
		   		'images/innovator/8/03.jpg',
		   		'images/innovator/8/04.jpg',
		   		'images/innovator/8/05.jpg',
		   		'images/innovator/8/06.jpg',
		   		'images/innovator/8/07.jpg',
		   		'images/innovator/8/08.jpg',
		   		'images/innovator/8/09.jpg',
		   		'images/innovator/8/10.jpg',
		   		'images/innovator/8/11.jpg',
		   		'images/innovator/8/12.jpg',
		   		'images/innovator/8/13.jpg',
		   		'images/innovator/8/14.jpg',
		   		'images/innovator/8/15.jpg',
		   	],
		   	"position"	: "18.787637, 98.966678",
		   	"price" : 800
		 },{
		 	"id" : 9,
		   "name": "ฮักเน้อ",
		   "address": "แม่ริม, เชียงใหม่",
		   "type": 2,
		   "storeType": "ร้านกาแฟ",
		   "rentType": "แบ่งพื้นที่ภายในร้าน",
		   "description": "ร้านกาแฟแห่งนี้มีพื้นที่กว้างขวาง  ตั้งแต่ที่จอดรถ จอดได้หน้าร้าน้สะดวก และบริเวณโดยรอบของร้าน สามารถเดินเล่น และนั่งเล่นได้ตามสบาย มีการตกแต่งเกี่ยวกับจักรยาน เพราะเจ้าของเป็นคนรักการปั่นจักรยาน และมักจะมีกลุ่มคนปั่นจักรยานแวะเวียนมาดื่มบ่อยๆ บริเวณภายในตัวร้าน สามารถรับคนได้ประมาณ 20 คน",
		   "amenities": ["แอร์","ไฟโคม","โต๊ะ","เก้าอี้","ชั้นวางของ","ตู้เย็น","ตู้ไอสครีม","เครื่องชงกาแฟ","ลานจอดรถ"],
		   "rule": "ไม่ขายของปลอม , ไม่ขายของผิดกฏหมาย , ไม่ทำให้สถานที่เลอะเทอะ",
		   "images" : [
		   		'images/innovator/9/01.jpg',
		   		'images/innovator/9/02.jpg',
		   		'images/innovator/9/03.jpg',
		   		'images/innovator/9/04.jpg',
		   		'images/innovator/9/05.jpg',
		   		'images/innovator/9/06.jpg',
		   		'images/innovator/9/07.jpg',
		   		'images/innovator/9/08.jpg',
		   		'images/innovator/9/09.jpg',
		   		'images/innovator/9/10.jpg',
		   		'images/innovator/9/11.jpg'
		   	],
		   	"position"	: "18.982975, 98.909119",
		   	"price" : 600 
		 }
// 		 ,{
// 		 	"id" : 10,
// 		   "name": "Sher",
// 		   "address": "สยามสแควร์วัน",
// 		   "type": 3,
// 		   "storeType": "ร้านขายของฝาก",
// 		   "rentType": "แบ่งพื้นที่ภายในร้าน",
// 		   "description": "ร้านของเราเน้นขายสินค้าประเภทของฝาก โดยจะเน้นไปที่อาหารที่กินง่าย ซื้อสะดวก โดยลูกค้าหลักคือคนจีน 90% 
// ส่วนที่เราปล่อยให้เช่าคือ ชั้นวางกระจก 2 ชั้น โดยเป็นส่วนหนึ่งของเคาท์เตอร์คิดเงิน ทุกคนที่มาจ่ายเงินจะเห็นชั้นวางนี้ทุกคน ขนาดของชั้นวาง ประมาณ 1x2 ฟุต มีสองชั้น พร้อมมีไฟเปิดเพื่อให้สินถ้าโดดเด่น",
// 		   "amenities": ["แอร์","หลอดไฟส่องสินค้า","ผู้ช่วยขายคนจีน"],
// 		   "rule": "ไม่ขายของปลอม , ไม่ขายของผิดกฏหมาย",
// 		   "images" : [
// 		   		'images/innovator/10/01.jpg',
// 		   		'images/innovator/10/02.jpg',
// 		   		'images/innovator/10/03.jpg',
// 		   		'images/innovator/10/04.jpg',
// 		   		'images/innovator/10/05.jpg',
// 		   		'images/innovator/10/06.jpg',
// 		   		'images/innovator/10/07.jpg',
// 		   		'images/innovator/10/08.jpg',
// 		   		'images/innovator/10/09.jpg',
// 		   		'images/innovator/10/10.jpg',
// 		   		'images/innovator/10/11.jpg',
// 		   		'images/innovator/10/12.jpg',
// 		   		'images/innovator/10/13.jpg',
// 		   		'images/innovator/10/14.jpg'
// 		   	],
// 		   	"position"	: "13.745285, 100.533850",
// 		   	"price" : 1000
// 		 },

		];

	return Store;

});